hard_tabs = false
normalize_comments = true
format_strings = true
format_macro_matchers = true
fn_single_line = true
imports_layout = "HorizontalVertical"
imports_granularity="Crate"
struct_field_align_threshold = 30
enum_discrim_align_threshold = 10
match_block_trailing_comma = true
use_field_init_shorthand = true
report_fixme = "Always"
